using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using DataLayer;
using UI_Application.Models;
using UI_Application.Services;

namespace UI_Application.ViewModels;

/// <summary>
/// ViewModel for the text editor with typesetting capabilities.
/// </summary>
public class EditorViewModel : INotifyPropertyChanged
{
    private string _text = string.Empty;
    private ObservableCollection<GlyphInfo> _glyphs = new();
    private ObservableCollection<PageModel> _pages = new();
    private PageModel? _currentPage;
    private readonly DatabaseContext _database;
    private readonly PaginationEngine _paginationEngine;
    private int _lastGlyphCount = 0;
    private string _statusMessage = "מוכן";
    
    // Live Update properties
    private string _extractedMainText = string.Empty;
    private ObservableCollection<string> _extractedFootnotesA = new();
    private ObservableCollection<string> _extractedFootnotesB = new();
    private ObservableCollection<string> _extractedFootnotesC = new();

    /// <summary>
    /// Status message for the StatusBar.
    /// </summary>
    public string StatusMessage
    {
        get => _statusMessage;
        set
        {
            if (_statusMessage != value)
            {
                _statusMessage = value;
                OnPropertyChanged();
            }
        }
    }

    /// <summary>
    /// Input text for typesetting.
    /// </summary>
    public string Text
    {
        get => _text;
        set
        {
            if (_text != value)
            {
                _text = value;
                OnPropertyChanged();
                // Live Update: Extract and update analysis area
                UpdateTextAnalysis();
            }
        }
    }
    
    /// <summary>
    /// Extracted main text for analysis display (Live Update).
    /// </summary>
    public string ExtractedMainText
    {
        get => _extractedMainText;
        private set
        {
            _extractedMainText = value;
            OnPropertyChanged();
        }
    }
    
    /// <summary>
    /// Extracted footnotes A for analysis display (Live Update).
    /// </summary>
    public ObservableCollection<string> ExtractedFootnotesA
    {
        get => _extractedFootnotesA;
        private set
        {
            _extractedFootnotesA = value;
            OnPropertyChanged();
        }
    }
    
    /// <summary>
    /// Extracted footnotes B for analysis display (Live Update).
    /// </summary>
    public ObservableCollection<string> ExtractedFootnotesB
    {
        get => _extractedFootnotesB;
        private set
        {
            _extractedFootnotesB = value;
            OnPropertyChanged();
        }
    }
    
    /// <summary>
    /// Extracted footnotes C for analysis display (Live Update).
    /// </summary>
    public ObservableCollection<string> ExtractedFootnotesC
    {
        get => _extractedFootnotesC;
        private set
        {
            _extractedFootnotesC = value;
            OnPropertyChanged();
        }
    }

    /// <summary>
    /// Collection of glyphs generated by the typesetting engine.
    /// </summary>
    public ObservableCollection<GlyphInfo> Glyphs
    {
        get => _glyphs;
        private set
        {
            _glyphs = value;
            OnPropertyChanged();
        }
    }

    /// <summary>
    /// Collection of pages generated by the pagination engine.
    /// </summary>
    public ObservableCollection<PageModel> Pages
    {
        get => _pages;
        private set
        {
            _pages = value;
            OnPropertyChanged();
        }
    }

    /// <summary>
    /// The currently selected/visible page.
    /// </summary>
    public PageModel? CurrentPage
    {
        get => _currentPage;
        set
        {
            if (_currentPage != value)
            {
                _currentPage = value;
                OnPropertyChanged();
                // Load glyphs for current page
                if (_currentPage != null)
                {
                    LoadGlyphsForPage(_currentPage);
                }
            }
        }
    }

    /// <summary>
    /// Command to execute typesetting layout.
    /// </summary>
    public ICommand LayoutCommand { get; }

    public EditorViewModel()
    {
        // Initialize SQLite database in user's app data folder
        var dbPath = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "TypesettingApp",
            "typesetting.db");
        
        Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!);
        _database = new DatabaseContext(dbPath);
        
        _paginationEngine = new PaginationEngine(pageWidth: 800, pageHeight: 600);
        
        LayoutCommand = new RelayCommand(ExecuteLayout);
    }

    /// <summary>
    /// Call the C++ typesetting engine to layout the text and save to database.
    /// </summary>
    private void ExecuteLayout()
    {
        try
        {
            if (string.IsNullOrEmpty(Text))
            {
                Glyphs.Clear();
                Pages.Clear();
                CurrentPage = null;
                _lastGlyphCount = 0;
                StatusMessage = "אין טקסט לעימוד";
                return;
            }

            StatusMessage = "מבצע עימוד...";
            
            // Step 1: Use PaginationEngine to split text into pages
            var pages = _paginationEngine.Paginate(Text);
            
            // Update the observable collection
            Pages.Clear();
            foreach (var page in pages)
            {
                Pages.Add(page);
            }
            
            // Set first page as current
            CurrentPage = Pages.FirstOrDefault();
            
            // Update status
            StatusMessage = _paginationEngine.GetPaginationSummary(pages);
            
            // DEBUG: Show what footnotes were extracted
            var current = Pages.FirstOrDefault();
            if (current != null)
            {
                var footnotesADetail = string.Join("\n---\n", current.FootnoteA.Select((f, i) => $"הערה א' {i+1}: {f}"));
                var footnotesBDetail = string.Join("\n---\n", current.FootnoteB.Select((f, i) => $"הערה ב' {i+1}: {f}"));
                var footnotesCDetail = string.Join("\n---\n", current.FootnoteC.Select((f, i) => $"הערה ג' {i+1}: {f}"));
                MessageBox.Show($"הערות א' ({current.FootnoteA.Count}):\n{footnotesADetail}\n\nהערות ב' ({current.FootnoteB.Count}):\n{footnotesBDetail}\n\nהערות ג' ({current.FootnoteC.Count}):\n{footnotesCDetail}", 
                    "הערות שנחלצו", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            
            // Save to database
            SaveToDatabase();
        }
        catch (Exception ex)
        {
            StatusMessage = $"שגיאה: {ex.Message}";
            MessageBox.Show($"שגיאה בעימוד: {ex.GetType().Name}: {ex.Message}\n\nStack: {ex.StackTrace}", "שגיאה", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Load glyphs for a specific page using the C++ engine.
    /// </summary>
    private void LoadGlyphsForPage(PageModel page)
    {
        if (string.IsNullOrEmpty(page?.MainContent))
        {
            Glyphs.Clear();
            return;
        }

        // Allocate buffer for glyphs
        int maxGlyphs = page.MainContent.Length;
        GlyphInfo[] glyphArray = new GlyphInfo[maxGlyphs];
        int count = maxGlyphs;

        // Call the native C++ engine
        NativeMethods.LayoutText(page.MainContent, glyphArray, ref count);
        _lastGlyphCount = count;

        // Update the observable collection
        Glyphs.Clear();
        for (int i = 0; i < count; i++)
        {
            Glyphs.Add(glyphArray[i]);
        }
        
        // Trigger UI update
        OnPropertyChanged(nameof(Glyphs));
    }
    
    /// <summary>
    /// Live Update: Extract text and footnotes and update analysis area.
    /// </summary>
    private void UpdateTextAnalysis()
    {
        if (string.IsNullOrEmpty(Text))
        {
            ExtractedMainText = string.Empty;
            ExtractedFootnotesA.Clear();
            ExtractedFootnotesB.Clear();
            ExtractedFootnotesC.Clear();
            return;
        }
        
        var (main, fA, fB, fC) = TextHelper.ExtractContentAndFootnotes(Text);
        
        ExtractedMainText = main;
        
        ExtractedFootnotesA.Clear();
        foreach (var note in fA) ExtractedFootnotesA.Add(note);
        
        ExtractedFootnotesB.Clear();
        foreach (var note in fB) ExtractedFootnotesB.Add(note);
        
        ExtractedFootnotesC.Clear();
        foreach (var note in fC) ExtractedFootnotesC.Add(note);
    }

    /// <summary>
    /// Save the input text and pagination info to SQLite database.
    /// </summary>
    private void SaveToDatabase()
    {
        try
        {
            var content = new TextContent
            {
                Content = $"{Text} (Pages: {Pages.Count}, Glyphs: {_lastGlyphCount})",
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow
            };
            _database.SaveContent(content.Content);
        }
        catch (Exception ex)
        {
            StatusMessage = $"שגיאה: {ex.Message}";
            MessageBox.Show($"שגיאה בשמירה לדטאבייס: {ex.GetType().Name}: {ex.Message}\n\nStack: {ex.StackTrace}", "שגיאה", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Get all saved content from database (for history view).
    /// </summary>
    public List<TextContent> GetSavedContent()
    {
        return _database.GetAllContent();
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    protected virtual void OnPropertyChanged([CallerMemberName] string? propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}

/// <summary>
/// Simple relay command implementation.
/// </summary>
public class RelayCommand : ICommand
{
    private readonly Action _execute;
    private readonly Func<bool>? _canExecute;

    public RelayCommand(Action execute, Func<bool>? canExecute = null)
    {
        _execute = execute ?? throw new ArgumentNullException(nameof(execute));
        _canExecute = canExecute;
    }

    public bool CanExecute(object? parameter)
    {
        return _canExecute?.Invoke() ?? true;
    }

    public void Execute(object? parameter)
    {
        _execute();
    }

    public event EventHandler? CanExecuteChanged
    {
        add { CommandManager.RequerySuggested += value; }
        remove { CommandManager.RequerySuggested -= value; }
    }
}
